user:
  name: oliver
  uid: 1000
  group: oliver
  shell: /usr/bin/zsh
  email: oliver.e.larsson@gmail.com
  log:
    dir: log
    rotate: 8

# dotfiles:
#     url: git@github.com:pigmonkey/dotfiles.git
#     destination: projects/dotfiles
#     rcup_flags: -fx README.md

ssh:
  port: 22
  enable_sshd: True

network:
  spoof_mac: True

editors:
  pacman:
    - vi
    - nano
    - vim
    - neovim
  aur:
    - visual-studio-code-bin

video_drivers:
  - intel-media-driver

base_packages:
  - base-devel
  - man-db
  - man-pages
  - pacman-contrib
  - git
  - rsync
  - coreutils
  - moreutils
  - dateutils
  - screen
  - cpulimit
  - htop
  - gnupg
  - tldr

passwordless_sudo:
  - /usr/bin/openvpn*

bluetooth:
  disable: False

journal:
  max_size: 256M

udisks:
  auto_mount: True
  shared_mount: True

fonts:
  pacman:
    - adobe-source-code-pro-fonts
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - terminus-font
    - tex-gyre-fonts
    - ttf-caladea
    - ttf-carlito
    - ttf-dejavu
    - ttf-droid
    - ttf-fira-mono
    - ttf-ibm-plex
    - ttf-inconsolata
    - ttf-liberation
    - ttf-opensans
    - ttf-ubuntu-font-family
  aur:
    - ttf-bitstream-charter
    - ttf-cooper-hewitt
    - ttf-courier-prime
    - ttf-heuristica
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-oswald
    - ttf-quintessential
    - ttf-signika
    - nerd-fonts-complete
