user:
  name: oliver
  uid: 1000
  group: oliver
  shell: /usr/bin/zsh
  email: oliver.e.larsson@gmail.com
  log:
    dir: log
    rotate: 8

hostname: ratchet

interception:
  caps2esc:
    enabled: True
    mode: 1
    delay: 20000

# dotfiles:
#     url: git@github.com:pigmonkey/dotfiles.git
#     destination: projects/dotfiles
#     rcup_flags: -fx README.md

aur:
  dir: aur
  packages:
    - yay

ssh:
  port: 22
  # user_key: /root/id_rsa
  enable_sshd: True

gnupg:
  enable_agent: True
  emulate_ssh: True

network:
  spoof_mac: True
  # conn_check:
  #   interval: 0
  # trusted_uuid:
  #   - 39744b35-2f2f-4a18-9da4-7542a56c28c2
  #   - d2642f7e-9e58-4b00-82f8-26b4ef76a54e
  #   - b21284e6-01af-492f-8bea-45a69ef22a23
  #   - f74f2bd5-8748-4e1e-98f9-dae2dd44b916

editors:
  pacman:
    - vi
    - nano
    - vim
    - neovim
  aur:
    - visual-studio-code-bin

video_drivers:
  - intel-media-driver

base_packages:
  - base-devel
  - man-db
  - man-pages
  - pacman-contrib
  - git
  - rsync
  - coreutils
  - moreutils
  - dateutils
  - ruby
  - screen
  - cpulimit

filesystem_packages:
  - exfat-utils
  - gparted

passwordless_sudo:
  - /usr/bin/openvpn*

bluetooth:
  disable: False

journal:
  max_size: 256M

udisks:
  auto_mount: True
  shared_mount: True

libinput:
  # middle_click_scroll: 12
  # button_mapping: "1 2 3 4 5 6 7 8 9 10 11 2"

base_fonts:
  - adobe-source-code-pro-fonts
  - cantarell-fonts
  - gsfonts
  - noto-fonts
  - terminus-font
  - tex-gyre-fonts
  - ttf-caladea
  - ttf-carlito
  - ttf-dejavu
  - ttf-droid
  - ttf-fira-mono
  - ttf-ibm-plex
  - ttf-inconsolata
  - ttf-liberation
  - ttf-opensans
  - ttf-ubuntu-font-family

aur_fonts:
  - ttf-bitstream-charter
  - ttf-cooper-hewitt
  - ttf-courier-prime
  - ttf-heuristica
  - ttf-merriweather
  - ttf-merriweather-sans
  - ttf-oswald
  - ttf-quintessential
  - ttf-signika
  - nerd-fonts-complete

kernel_parameters: "quiet consoleblank=60"
