---
- name: Install editors
  pacman:
    name: "{{ editors.pacman }}"
    state: present

- name: Install AUR editors
  yay:
    name: "{{ editors.aur }}"
    state: present
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install Language Servers
  pacman:
    name: "{{ lsp_servers.pacman }}"
    state: present
