---
- hosts: localhost
  become: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: sysmon, tags: ["sysmon"] }
    - { role: cron, tags: ["cron"] }
    - role: microcode
      tags: ["microcode"]
      when: "'GenuineIntel' in ansible_processor"
    - { role: ssh, tags: ["ssh"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: ssd, tags: ["ssd"] }
    - role: interception
      tags: ["interception"]
      when: "interception is defined"
    - { role: fonts, tags: ["fonts"] }
    - { role: xorg, tags: ["xorg"] }
    - { role: alacritty, tags: ["alacritty"] }
    - { role: lightdm, tags: ["lightdm"] }
    - { role: i3, tags: ["i3"] }
    - { role: gtk, tags: ["gtk"] }
    - { role: iptables, tags: ["iptables"] }
    - { role: nettools, tags: ["nettools"] }
    - { role: networkmanager, tags: ["networkmanager"] }
    - { role: macchiato, tags: ["macchiato"] }
    - { role: ntp, tags: ["ntp"] }
    - { role: editors, tags: ["editors"] }
    - { role: filesystems, tags: ["filesystems"] }
    - { role: archive, tags: ["archive"] }
    - { role: spell, tags: ["spell"] }
    - { role: udisks, tags: ["udisks"] }
    - { role: browsers, tags: ["browsers"] }
    - { role: media, tags: ["media"] }
    - { role: laptop, tags: ["laptop"] }
    - { role: cups, tags: ["cups"] }
    - { role: office, tags: ["office"] }
    - { role: pdf, tags: ["pdf"] }
    - { role: virtualbox, tags: ["virtualbox"] }
    - { role: golang, tags: ["golang"] }
    - { role: sound, tags: ["sound"] }
    - { role: bluetooth, tags: ["bluetooth"] }

  vars_prompt:
    - name: user_password
      prompt: "Enter user password"
