---
- name: Bootstrap
  hosts: localhost
  become: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: yay, tags: ["yay", "aur"] }
    - { role: cron, tags: ["cron"] }
    - { role: microcode, tags: ["microcode"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: interception, tags: ["interception"] }
    - { role: xorg, tags: ["xorg"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: terminal, tags: ["terminal"] }
    - { role: ly, tags: ["ly"] }
    - { role: i3, tags: ["i3"] }
    - { role: gtk, tags: ["gtk"] }
    - { role: iptables, tags: ["iptables"] }
    - { role: networkmanager, tags: ["networkmanager"] }
    - { role: ntp, tags: ["ntp"] }
    - { role: editors, tags: ["editors"] }
    - { role: archive, tags: ["archive"] }
    - { role: usbmount, tags: ["usbmount"] }
    - { role: browsers, tags: ["browsers"] }
    - { role: media, tags: ["media"] }
    - { role: laptop, tags: ["laptop"] }
    - { role: office, tags: ["office"] }
    - { role: pdf, tags: ["pdf"] }
    - { role: virtualbox, tags: ["virtualbox"] }
    - { role: sound, tags: ["sound"] }
    - { role: bluetooth, tags: ["bluetooth"] }
    - { role: docker, tags: ["docker"] }
    - { role: kubernetes, tags: ["kubernetes"] }

  vars_prompt:
    - name: user_password
      prompt: "Enter user password"
    - name: hostname
      prompt: "Enter machine hostname"
      private: false
