---
- name: Install Xorg
  pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  ansible.builtin.pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  ansible.builtin.pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  ansible.builtin.pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  ansible.builtin.pacman:
    name: xorg-xev
    state: present

- name: Install xclip
  ansible.builtin.pacman:
    name: xclip
    state: present

- name: Install xorg-sessreg
  ansible.builtin.pacman:
    name: xorg-sessreg
    state: present

- name: Install xorg-xwininfo
  ansible.builtin.pacman:
    name: xorg-xwininfo
    state: present

- name: Install xautomation
  ansible.builtin.pacman:
    name: xautomation
    state: present

- name: Install arandr
  ansible.builtin.pacman:
    name: arandr
    state: present

- name: Install brightnessctl
  ansible.builtin.pacman:
    name: brightnessctl
    state: present

- name: Install video driver(s)
  ansible.builtin.pacman:
    name: "{{ video_drivers }}"
    state: present

- name: Add user to video group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: video
    append: true
  tags:
    - user

- ansible.builtin.include_tasks: unclutter.yml
- ansible.builtin.include_tasks: autorandr.yml
- ansible.builtin.include_tasks: autocutsel.yml
- ansible.builtin.include_tasks: xdg.yml
- ansible.builtin.include_tasks: picom.yml
