---
- name: Install Xorg
  pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  ansible.builtin.pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  ansible.builtin.pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  ansible.builtin.pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  ansible.builtin.pacman:
    name: xorg-xev
    state: present

- name: Install xorg-sessreg
  ansible.builtin.pacman:
    name: xorg-sessreg
    state: present

- name: Install xorg-xwininfo
  ansible.builtin.pacman:
    name: xorg-xwininfo
    state: present

- name: Install xautomation
  ansible.builtin.pacman:
    name: xautomation
    state: present

- name: Install arandr
  ansible.builtin.pacman:
    name: arandr
    state: present

- name: Install brightnessctl
  ansible.builtin.pacman:
    name: brightnessctl
    state: present

- name: Install video driver(s)
  ansible.builtin.pacman:
    name: "{{ video_drivers }}"
    state: present

- name: Add user to video group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: video
    append: true
  tags:
    - user

- name: Enable middle-click scrolling
  ansible.builtin.template:
    src: 30-scroll.conf
    dest: /etc/X11/xorg.conf.d/30-scroll.conf
    mode: 0644
  when: libinput.middle_click_scroll is defined
  tags:
    - libinput

- name: Remap mouse buttons
  ansible.builtin.template:
    src: 30-button_mapping.conf
    dest: /etc/X11/xorg.conf.d/30-button_mapping.conf
    mode: 0644
  when: libinput.button_mapping is defined
  tags:
    - libinput

- include: unclutter.yml
- include: autorandr.yml
- include: autocutsel.yml
- include: xdg.yml
- include: picom.yml
