---
- name: Install xdg-user-dirs
  ansible.builtin.pacman:
    name: xdg-user-dirs
    state: present
  tags:
    - xdg

- name: Create user directories
  ansible.builtin.command: /usr/bin/xdg-user-dirs-update
  changed_when: true
  become: true
  become_user: "{{ user.name }}"
  tags:
    - xdg

- name: Install perl-file-mimeinfo
  ansible.builtin.pacman:
    name: perl-file-mimeinfo
    state: present
  tags:
    - xdg
