---
- name: Clone user dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    accept_hostkey: true
    update: true
    version: "{{ dotfiles.version }}"
  when: dotfiles is defined
  become: true
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  ansible.builtin.command:
    cmd: ./"{{ dotfiles.install_script }}"
    chdir: /home/{{ user.name }}/{{ dotfiles.destination }}
  when: dotfiles is defined
  become: true
  become_user: "{{ user.name }}"

- name: Make sure ~/.shell_local_before exists.
  ansible.builtin.lineinfile:
    path: /home/{{ user.name }}/.shell_local_before
    create: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    line: "#!/usr/bin/sh"

- name: Set local dotfile repository path.
  ansible.builtin.lineinfile:
    path: /home/{{ user.name }}/.shell_local_before
    regexp: "^export LOCAL_DOTFILES_REPOSITORY="
    line: "export LOCAL_DOTFILES_REPOSITORY=/home/{{ user.name }}/{{ dotfiles.destination }}"
  when: dotfiles is defined

