---
- name: Clone user dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    accept_hostkey: true
    update: false
    version: origin/HEAD
  when: dotfiles is defined
  become: true
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  ansible.builtin.command:
    cmd: ./"{{ dotfiles.install_script }}"
    chdir: /home/{{ user.name }}/{{ dotfiles.destination }}
  when: dotfiles is defined
  become: true
  become_user: "{{ user.name }}"
