---
- name: Install Okular
  pacman:
    name: okular
    state: present
  tags:
    - okular

- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep

- name: Install zathura
  ansible.builtin.pacman:
    name:
      - zathura
      - zathura-pdf-mupdf
    state: present
