---
- name: Install OpenSSH
  ansible.builtin.pacman:
    name: openssh
    state: present

- name: Push OpenSSH daemon configuration file
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify:
    - restart sshd

- name: Enable and start OpenSSH
  ansible.builtin.service:
    name: sshd.service
    enabled: true
    state: started
  when: ssh.enable_sshd

- name: Disable and stop OpenSSH
  ansible.builtin.service:
    name: sshd.service
    enabled: false
    state: stopped
  when: not ssh.enable_sshd
