---
- name: Install gtk
  ansible.builtin.pacman:
    name:
      - gtk2
      - gtk3
    state: present

- name: Install lxappearance
  ansible.builtin.pacman:
    name: lxappearance
    state: present

- name: Clone nordic theme
  ansible.builtin.git:
    repo: https://github.com/EliverLara/Nordic.git
    dest: /usr/share/themes/Nordic-darker
    update: true
    version: darker

- name: Download zafiro icons
  ansible.builtin.unarchive:
    src: https://github.com/zayronxio/Zafiro-icons/releases/download/1.3/Zafiro-Icons-Dark.tar.xz
    dest: /usr/share/icons
    remote_src: true
