---
- include_tasks: tlp.yml

- name: Copy touchpad configuration file
  copy: src=30-touchpad.conf dest=/etc/X11/xorg.conf.d/30-touchpad.conf
  tags:
    - libinput

- name: Copy logind configuration file
  copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Install powertop
  pacman: name=powertop state=present
