---
- name: Install macchiato
  become: true
  become_user: "{{ user.name }}"
  yay:
    name: macchiato-git
  tags:
    - aur

- name: Configure interfaces for macchiato
  ansible.builtin.copy:
    src: macchiato_default.sh
    dest: /etc/macchiato.d/{{ item }}.sh
    mode: 0755
  with_items: "{{ ansible_interfaces }}"

- name: Enable macchiato
  ansible.builtin.service:
    name: macchiato.service
    enabled: true
  when: network.spoof_mac
  notify:
    - start macchiato

- name: Disable and stop macchiato
  ansible.builtin.service:
    name: macchiato.service
    enabled: false
    state: stopped
  when: network.spoof_mac
