---
- name: Install i3
  ansible.builtin.pacman:
    name:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - dmenu
    state: present

- name: Verify that default applications file exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/xdg/mimeapps.list
    force: false
    mode: 0666

- name: Verify header in default applications file
  ansible.builtin.lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: "[Default Applications]"
    insertbefore: BOF
