---
- name: Install VirtualBox and dependencies
  pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-modules-arch
    state: present

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
  tags:
    - user
