---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
    state: present
  tags:
    - zip

- name: Install unrar
  pacman:
    name: unrar
    state: present
  tags:
    - unrar

- name: Install thunar
  pacman:
    name: 
      - thunar
      - thunar-archive-plugin
    state: present
  tags:
    - thunar

- name: Install file-roller
  ansible.builtin.pacman:
    name: file-roller
    state: present
  tags:
    - file-roller
