---
- name: Install docker
  ansible.builtin.pacman:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
