---
- name: Copy pacman configuration file
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644

- name: Refresh pacman mirrors
  community.general.pacman:
    update_cache: true

- name: Install inetutils for hostname
  community.general.pacman:
    name: inetutils
    state: present

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- ansible.builtin.import_tasks: shell.yml
- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: sudo.yml
- ansible.builtin.import_tasks: packages.yml
- ansible.builtin.import_tasks: journal.yml
