---
- name: Install NetworkManager and dependencies
  ansible.builtin.pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet
      - xfce4-notifyd
      - gnome-keyring
    state: present

- name: Push connectivity check config
  ansible.builtin.template:
    src: connectivity.conf.j2
    dest: /etc/NetworkManager/conf.d/20-connectivity.conf
    mode: 0644
  when: network.conn_check is defined

- name: Enable and start NetworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true
    state: started

- name: Enable and start NetworkManager dispatcher
  ansible.builtin.service:
    name: NetworkManager-dispatcher.service
    enabled: true
    state: started

- name: Disable dhcpcd service
  ansible.builtin.service:
    name: dhcpcd.service
    enabled: false
